# Auto-assign configuration
# https://github.com/kentaro-m/auto-assign-action

# Add reviewers to pull requests
addReviewers: true

# Add assignees to pull requests
addAssignees: author

# A list of reviewers to be added to pull requests (GitHub user names)
reviewers:
  - rob9206

# A number of reviewers added to the pull request
numberOfReviewers: 1

# A list of assignees, overrides reviewers if set
# assignees:
#   - rob9206

# A number of assignees to add to the pull request
# Set to 0 to add all the assignees
# numberOfAssignees: 1

# A list of keywords to be skipped from review
skipKeywords:
  - wip
  - WIP
  - draft

# Run only on draft pull requests
# runOnDraft: true
