"""
Tuning Workspace Service.

Provides a first-class data model for organizing work on a specific vehicle:

    Vehicle          -- the bike (identity that survives across jobs)
      TuningSession  -- one tuning job on that bike
        Iteration    -- one flash cycle within the session (iter_0 = baseline)

On-disk layout:

    vehicles/
      <vehicle_id>/
        profile.json
        sessions/
          <session_id>/
            session.json
            base_tune/               (immutable archive of flashed base PVV)
              base.pvv
            iterations/
              iter_0/
                iteration.json
                pulls/               (WP8, TXT, PV-CSV captured under this flash)
                patches/             (PVV patches generated by DynoAI)
                analyses/            (NextGen / AutoTune payloads)
              iter_1/ ...

Disk is the source of truth. JSON sidecar files make each entity self-describing.
This replaces the hand-routed OneDrive folder workflow used on the Racile job.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import threading
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

__all__ = [
    "Vehicle",
    "TuningSession",
    "Iteration",
    "SessionStatus",
    "TuningWorkspace",
    "WorkspaceError",
    "get_workspace",
]

# =============================================================================
# Errors
# =============================================================================


class WorkspaceError(Exception):
    """Raised on workspace invariant violations."""


# =============================================================================
# Dataclasses
# =============================================================================


@dataclass
class Vehicle:
    """A tuned vehicle. Identity survives across all sessions for this bike."""

    id: str
    name: str
    year: Optional[int] = None
    make: str = ""
    model: str = ""
    displacement_ci: Optional[float] = None
    ecu_signature: Optional[str] = None
    watch_folder: Optional[str] = None
    notes: str = ""
    created_at: str = field(default_factory=lambda: _utc_now())
    updated_at: str = field(default_factory=lambda: _utc_now())

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class TuningSession:
    """One tuning job on a specific vehicle. Has a base tune + N iterations."""

    id: str
    vehicle_id: str
    base_tune_sha256: Optional[str] = None
    status: str = "active"
    notes: str = ""
    created_at: str = field(default_factory=lambda: _utc_now())
    updated_at: str = field(default_factory=lambda: _utc_now())
    active_iteration_id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class Iteration:
    """One flash cycle. iter_0 is the baseline (no patch applied yet)."""

    id: str
    session_id: str
    index: int
    patch_filename: Optional[str] = None
    flashed_at: Optional[str] = None
    notes: str = ""
    created_at: str = field(default_factory=lambda: _utc_now())

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class SessionStatus:
    """Computed readiness checklist for a session's active iteration."""

    session_id: str
    iteration_id: Optional[str]
    has_vehicle: bool
    has_base_tune: bool
    pull_count: int
    has_afr_data: bool
    ready_to_analyze: bool
    checklist: list[dict[str, Any]]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# =============================================================================
# Helpers
# =============================================================================

_SLUG_RE = re.compile(r"[^a-z0-9_-]+")


def _utc_now() -> str:
    """UTC ISO-8601 with Z suffix, millisecond precision."""
    return (
        datetime.now(timezone.utc)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )


def slugify(value: str) -> str:
    """Lowercase kebab-ish slug safe for filesystem use."""
    v = value.strip().lower()
    v = v.replace(" ", "_")
    v = _SLUG_RE.sub("", v)
    v = v.strip("-_")
    return v or "untitled"


def _atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, default=str),
        encoding="utf-8",
    )
    tmp.replace(path)


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_file(path: Path, bufsize: int = 65536) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while chunk := f.read(bufsize):
            h.update(chunk)
    return h.hexdigest()


# =============================================================================
# Workspace
# =============================================================================


class TuningWorkspace:
    """Disk-backed workspace. Thread-safe for common concurrent operations."""

    VEHICLES_DIRNAME = "vehicles"
    SESSIONS_DIRNAME = "sessions"
    ITERATIONS_DIRNAME = "iterations"
    BASE_TUNE_DIRNAME = "base_tune"
    BASE_TUNE_FILENAME = "base.pvv"

    PULLS_DIRNAME = "pulls"
    PATCHES_DIRNAME = "patches"
    ANALYSES_DIRNAME = "analyses"

    def __init__(self, root: Optional[Path | str] = None) -> None:
        if root is None:
            root = Path.cwd() / self.VEHICLES_DIRNAME
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self._lock = threading.RLock()

    # -------------------------------------------------------------------------
    # Path helpers
    # -------------------------------------------------------------------------

    def vehicle_dir(self, vehicle_id: str) -> Path:
        return self.root / slugify(vehicle_id)

    def vehicle_profile(self, vehicle_id: str) -> Path:
        return self.vehicle_dir(vehicle_id) / "profile.json"

    def sessions_dir(self, vehicle_id: str) -> Path:
        return self.vehicle_dir(vehicle_id) / self.SESSIONS_DIRNAME

    def session_dir(self, vehicle_id: str, session_id: str) -> Path:
        return self.sessions_dir(vehicle_id) / slugify(session_id)

    def session_json(self, vehicle_id: str, session_id: str) -> Path:
        return self.session_dir(vehicle_id, session_id) / "session.json"

    def base_tune_path(self, vehicle_id: str, session_id: str) -> Path:
        return (
            self.session_dir(vehicle_id, session_id)
            / self.BASE_TUNE_DIRNAME
            / self.BASE_TUNE_FILENAME
        )

    def iterations_dir(self, vehicle_id: str, session_id: str) -> Path:
        return self.session_dir(vehicle_id, session_id) / self.ITERATIONS_DIRNAME

    def iteration_dir(
        self, vehicle_id: str, session_id: str, iteration_id: str
    ) -> Path:
        return self.iterations_dir(vehicle_id, session_id) / slugify(iteration_id)

    # -------------------------------------------------------------------------
    # Vehicles
    # -------------------------------------------------------------------------

    def list_vehicles(self) -> list[Vehicle]:
        vehicles: list[Vehicle] = []
        for child in sorted(self.root.iterdir()) if self.root.exists() else []:
            if child.is_dir() and (child / "profile.json").exists():
                try:
                    vehicles.append(self._load_vehicle_from_dir(child))
                except Exception:
                    continue
        return vehicles

    def create_vehicle(
        self,
        name: str,
        year: Optional[int] = None,
        make: str = "",
        model: str = "",
        displacement_ci: Optional[float] = None,
        vehicle_id: Optional[str] = None,
        watch_folder: Optional[str] = None,
        notes: str = "",
    ) -> Vehicle:
        with self._lock:
            vid = slugify(vehicle_id or name)
            if not vid:
                raise WorkspaceError("vehicle id/name cannot be empty")

            vpath = self.vehicle_dir(vid)
            if vpath.exists():
                raise WorkspaceError(f"vehicle already exists: {vid}")

            vehicle = Vehicle(
                id=vid,
                name=name,
                year=year,
                make=make,
                model=model,
                displacement_ci=displacement_ci,
                watch_folder=watch_folder,
                notes=notes,
            )
            vpath.mkdir(parents=True, exist_ok=False)
            (vpath / self.SESSIONS_DIRNAME).mkdir(exist_ok=True)
            _atomic_write_json(self.vehicle_profile(vid), vehicle.to_dict())
            return vehicle

    def get_vehicle(self, vehicle_id: str) -> Vehicle:
        profile = self.vehicle_profile(vehicle_id)
        if not profile.exists():
            raise WorkspaceError(f"vehicle not found: {vehicle_id}")
        return self._load_vehicle_from_profile(profile)

    def update_vehicle(self, vehicle_id: str, **fields: Any) -> Vehicle:
        with self._lock:
            vehicle = self.get_vehicle(vehicle_id)
            for key, val in fields.items():
                if key in {"id", "created_at"}:
                    continue
                if hasattr(vehicle, key):
                    setattr(vehicle, key, val)
            vehicle.updated_at = _utc_now()
            _atomic_write_json(self.vehicle_profile(vehicle.id), vehicle.to_dict())
            return vehicle

    def find_vehicle_by_ecu_signature(self, signature: str) -> Optional[Vehicle]:
        if not signature:
            return None
        for vehicle in self.list_vehicles():
            if vehicle.ecu_signature and vehicle.ecu_signature == signature:
                return vehicle
        return None

    def _load_vehicle_from_profile(self, profile_path: Path) -> Vehicle:
        return Vehicle(**_read_json(profile_path))

    def _load_vehicle_from_dir(self, vehicle_dir: Path) -> Vehicle:
        return self._load_vehicle_from_profile(vehicle_dir / "profile.json")

    # -------------------------------------------------------------------------
    # Sessions
    # -------------------------------------------------------------------------

    def list_sessions(self, vehicle_id: str) -> list[TuningSession]:
        sdir = self.sessions_dir(vehicle_id)
        if not sdir.exists():
            return []
        sessions: list[TuningSession] = []
        for child in sorted(sdir.iterdir()):
            if child.is_dir() and (child / "session.json").exists():
                try:
                    sessions.append(TuningSession(**_read_json(child / "session.json")))
                except Exception:
                    continue
        return sessions

    def create_session(
        self,
        vehicle_id: str,
        session_id: Optional[str] = None,
        notes: str = "",
    ) -> TuningSession:
        with self._lock:
            self.get_vehicle(vehicle_id)

            if not session_id:
                session_id = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            sid = slugify(session_id)

            sdir = self.session_dir(vehicle_id, sid)
            if sdir.exists():
                raise WorkspaceError(f"session already exists: {sid}")

            session = TuningSession(id=sid, vehicle_id=slugify(vehicle_id), notes=notes)
            sdir.mkdir(parents=True, exist_ok=False)
            (sdir / self.BASE_TUNE_DIRNAME).mkdir(exist_ok=True)
            (sdir / self.ITERATIONS_DIRNAME).mkdir(exist_ok=True)
            _atomic_write_json(self.session_json(vehicle_id, sid), session.to_dict())

            iter0 = self._create_iteration_internal(vehicle_id, sid, index=0)
            session.active_iteration_id = iter0.id
            session.updated_at = _utc_now()
            _atomic_write_json(self.session_json(vehicle_id, sid), session.to_dict())

            return session

    def get_session(self, vehicle_id: str, session_id: str) -> TuningSession:
        spath = self.session_json(vehicle_id, session_id)
        if not spath.exists():
            raise WorkspaceError(f"session not found: {vehicle_id}/{session_id}")
        return TuningSession(**_read_json(spath))

    def update_session(
        self, vehicle_id: str, session_id: str, **fields: Any
    ) -> TuningSession:
        with self._lock:
            session = self.get_session(vehicle_id, session_id)
            for key, val in fields.items():
                if key in {"id", "vehicle_id", "created_at"}:
                    continue
                if hasattr(session, key):
                    setattr(session, key, val)
            session.updated_at = _utc_now()
            _atomic_write_json(
                self.session_json(vehicle_id, session_id), session.to_dict()
            )
            return session

    # -------------------------------------------------------------------------
    # Base tune
    # -------------------------------------------------------------------------

    def set_base_tune(
        self, vehicle_id: str, session_id: str, pvv_bytes: bytes
    ) -> dict[str, Any]:
        with self._lock:
            self.get_session(vehicle_id, session_id)
            dst = self.base_tune_path(vehicle_id, session_id)
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes(pvv_bytes)
            digest = _sha256_bytes(pvv_bytes)
            self.update_session(vehicle_id, session_id, base_tune_sha256=digest)
            return {"path": str(dst), "sha256": digest, "size": len(pvv_bytes)}

    def get_base_tune_path(self, vehicle_id: str, session_id: str) -> Optional[Path]:
        p = self.base_tune_path(vehicle_id, session_id)
        return p if p.exists() else None

    # -------------------------------------------------------------------------
    # Iterations
    # -------------------------------------------------------------------------

    def list_iterations(self, vehicle_id: str, session_id: str) -> list[Iteration]:
        idir = self.iterations_dir(vehicle_id, session_id)
        if not idir.exists():
            return []
        out: list[Iteration] = []
        for child in sorted(idir.iterdir()):
            if child.is_dir() and (child / "iteration.json").exists():
                try:
                    out.append(Iteration(**_read_json(child / "iteration.json")))
                except Exception:
                    continue
        out.sort(key=lambda i: i.index)
        return out

    def create_iteration(
        self,
        vehicle_id: str,
        session_id: str,
        patch_filename: Optional[str] = None,
    ) -> Iteration:
        with self._lock:
            self.get_session(vehicle_id, session_id)
            existing = self.list_iterations(vehicle_id, session_id)
            next_idx = max((i.index for i in existing), default=-1) + 1
            iteration = self._create_iteration_internal(
                vehicle_id,
                session_id,
                index=next_idx,
                patch_filename=patch_filename,
            )
            self.update_session(
                vehicle_id, session_id, active_iteration_id=iteration.id
            )
            return iteration

    def _create_iteration_internal(
        self,
        vehicle_id: str,
        session_id: str,
        index: int,
        patch_filename: Optional[str] = None,
    ) -> Iteration:
        iid = f"iter_{index}"
        idir = self.iteration_dir(vehicle_id, session_id, iid)
        if idir.exists():
            raise WorkspaceError(f"iteration already exists: {iid}")
        idir.mkdir(parents=True, exist_ok=False)
        (idir / self.PULLS_DIRNAME).mkdir(exist_ok=True)
        (idir / self.PATCHES_DIRNAME).mkdir(exist_ok=True)
        (idir / self.ANALYSES_DIRNAME).mkdir(exist_ok=True)
        iteration = Iteration(
            id=iid,
            session_id=slugify(session_id),
            index=index,
            patch_filename=patch_filename,
        )
        _atomic_write_json(idir / "iteration.json", iteration.to_dict())
        return iteration

    def get_iteration(
        self, vehicle_id: str, session_id: str, iteration_id: str
    ) -> Iteration:
        ijson = (
            self.iteration_dir(vehicle_id, session_id, iteration_id) / "iteration.json"
        )
        if not ijson.exists():
            raise WorkspaceError(f"iteration not found: {iteration_id}")
        return Iteration(**_read_json(ijson))

    def get_active_iteration(self, vehicle_id: str, session_id: str) -> Iteration:
        session = self.get_session(vehicle_id, session_id)
        if session.active_iteration_id:
            try:
                return self.get_iteration(
                    vehicle_id, session_id, session.active_iteration_id
                )
            except WorkspaceError:
                pass
        iters = self.list_iterations(vehicle_id, session_id)
        if not iters:
            raise WorkspaceError("session has no iterations")
        return iters[-1]

    # -------------------------------------------------------------------------
    # Artifact routing (used by sniffer + upload endpoint)
    # -------------------------------------------------------------------------

    def add_pull(
        self,
        vehicle_id: str,
        session_id: str,
        iteration_id: str,
        filename: str,
        data: bytes,
    ) -> Path:
        with self._lock:
            self.get_iteration(vehicle_id, session_id, iteration_id)
            pulls = (
                self.iteration_dir(vehicle_id, session_id, iteration_id)
                / self.PULLS_DIRNAME
            )
            pulls.mkdir(parents=True, exist_ok=True)
            dst = self._unique_path(pulls / filename)
            dst.write_bytes(data)
            return dst

    def add_patch(
        self,
        vehicle_id: str,
        session_id: str,
        iteration_id: str,
        filename: str,
        data: bytes,
    ) -> Path:
        with self._lock:
            self.get_iteration(vehicle_id, session_id, iteration_id)
            patches = (
                self.iteration_dir(vehicle_id, session_id, iteration_id)
                / self.PATCHES_DIRNAME
            )
            patches.mkdir(parents=True, exist_ok=True)
            dst = self._unique_path(patches / filename)
            dst.write_bytes(data)
            return dst

    def add_analysis(
        self,
        vehicle_id: str,
        session_id: str,
        iteration_id: str,
        filename: str,
        payload: dict[str, Any],
    ) -> Path:
        with self._lock:
            self.get_iteration(vehicle_id, session_id, iteration_id)
            analyses = (
                self.iteration_dir(vehicle_id, session_id, iteration_id)
                / self.ANALYSES_DIRNAME
            )
            analyses.mkdir(parents=True, exist_ok=True)
            dst = self._unique_path(analyses / filename)
            _atomic_write_json(dst, payload)
            return dst

    def list_pulls(
        self, vehicle_id: str, session_id: str, iteration_id: str
    ) -> list[Path]:
        pulls = (
            self.iteration_dir(vehicle_id, session_id, iteration_id)
            / self.PULLS_DIRNAME
        )
        if not pulls.exists():
            return []
        return sorted(p for p in pulls.iterdir() if p.is_file())

    def list_patches(
        self, vehicle_id: str, session_id: str, iteration_id: str
    ) -> list[Path]:
        patches = (
            self.iteration_dir(vehicle_id, session_id, iteration_id)
            / self.PATCHES_DIRNAME
        )
        if not patches.exists():
            return []
        return sorted(p for p in patches.iterdir() if p.is_file())

    def list_analyses(
        self, vehicle_id: str, session_id: str, iteration_id: str
    ) -> list[Path]:
        analyses = (
            self.iteration_dir(vehicle_id, session_id, iteration_id)
            / self.ANALYSES_DIRNAME
        )
        if not analyses.exists():
            return []
        return sorted(p for p in analyses.iterdir() if p.is_file())

    @staticmethod
    def _unique_path(target: Path) -> Path:
        """Avoid overwriting an existing file by appending -1, -2, ..."""
        if not target.exists():
            return target
        stem = target.stem
        suffix = target.suffix
        parent = target.parent
        n = 1
        while True:
            candidate = parent / f"{stem}-{n}{suffix}"
            if not candidate.exists():
                return candidate
            n += 1

    # -------------------------------------------------------------------------
    # Status / readiness
    # -------------------------------------------------------------------------

    AFR_EXTENSIONS = {".txt", ".csv"}
    PULL_EXTENSIONS = {".wp8", ".txt", ".csv"}

    def compute_status(self, vehicle_id: str, session_id: str) -> SessionStatus:
        try:
            session = self.get_session(vehicle_id, session_id)
        except WorkspaceError:
            return SessionStatus(
                session_id=session_id,
                iteration_id=None,
                has_vehicle=False,
                has_base_tune=False,
                pull_count=0,
                has_afr_data=False,
                ready_to_analyze=False,
                checklist=[
                    {
                        "id": "session",
                        "ok": False,
                        "label": "Session exists",
                        "detail": "session not found",
                    }
                ],
            )

        try:
            self.get_vehicle(vehicle_id)
            has_vehicle = True
        except WorkspaceError:
            has_vehicle = False

        has_base = self.get_base_tune_path(vehicle_id, session_id) is not None

        iteration: Optional[Iteration]
        try:
            iteration = self.get_active_iteration(vehicle_id, session_id)
        except WorkspaceError:
            iteration = None

        pulls: list[Path] = []
        has_afr = False
        if iteration is not None:
            pulls = self.list_pulls(vehicle_id, session_id, iteration.id)
            has_afr = any(p.suffix.lower() in self.AFR_EXTENSIONS for p in pulls)

        ready = has_vehicle and has_base and len(pulls) > 0

        checklist = [
            {
                "id": "vehicle",
                "ok": has_vehicle,
                "label": "Vehicle profile present",
                "detail": vehicle_id if has_vehicle else "missing vehicle record",
            },
            {
                "id": "base_tune",
                "ok": has_base,
                "label": "Base PVV uploaded",
                "detail": (
                    f"sha256={(session.base_tune_sha256 or '')[:12]}"
                    if has_base
                    else "drop the bike's current flashed PVV into the dropzone"
                ),
            },
            {
                "id": "active_iteration",
                "ok": iteration is not None,
                "label": "Active iteration",
                "detail": iteration.id if iteration else "no iterations yet",
            },
            {
                "id": "pulls",
                "ok": len(pulls) > 0,
                "label": "At least one dyno pull",
                "detail": f"{len(pulls)} pulls" if pulls else "drop WP8/TXT pulls",
            },
            {
                "id": "afr_data",
                "ok": has_afr,
                "label": "AFR data present (TXT or CSV)",
                "detail": (
                    "Dynojet TXT or Power Vision CSV recommended"
                    if not has_afr
                    else "ok"
                ),
            },
            {
                "id": "ready",
                "ok": ready,
                "label": "Ready to analyze",
                "detail": "run AutoTune/NextGen on this iteration" if ready else "",
            },
        ]

        return SessionStatus(
            session_id=session.id,
            iteration_id=iteration.id if iteration else None,
            has_vehicle=has_vehicle,
            has_base_tune=has_base,
            pull_count=len(pulls),
            has_afr_data=has_afr,
            ready_to_analyze=ready,
            checklist=checklist,
        )

    # -------------------------------------------------------------------------
    # Destructive (opt-in via callers that handle confirmation)
    # -------------------------------------------------------------------------

    def delete_vehicle(self, vehicle_id: str) -> None:
        with self._lock:
            vdir = self.vehicle_dir(vehicle_id)
            if vdir.exists():
                shutil.rmtree(vdir)

    def delete_session(self, vehicle_id: str, session_id: str) -> None:
        with self._lock:
            sdir = self.session_dir(vehicle_id, session_id)
            if sdir.exists():
                shutil.rmtree(sdir)


# =============================================================================
# Global singleton (configured via env or default "vehicles/")
# =============================================================================

_workspace: Optional[TuningWorkspace] = None
_workspace_lock = threading.Lock()


def get_workspace(root: Optional[Path | str] = None) -> TuningWorkspace:
    """Get the process-wide workspace. `root` is used on first call only."""
    global _workspace
    with _workspace_lock:
        if _workspace is None or root is not None:
            if root is None:
                import os

                root = os.environ.get("DYNOAI_WORKSPACE_ROOT", "vehicles")
            _workspace = TuningWorkspace(root=root)
        return _workspace


def reset_workspace() -> None:
    """Reset the singleton (testing only)."""
    global _workspace
    with _workspace_lock:
        _workspace = None
