"""
Content sniffer for uploads into a TuningWorkspace.

Routes each uploaded file by its *bytes*, not its filename:

    WP8                  -> pulls    (dyno run binary, FECEFACE magic)
    Dynojet TXT export   -> pulls    (tab-delimited w/ mph + LC1/LC2)
    Power Vision CSV log -> pulls    ("Dynojet Power Vision Log File" header)
    PVV                  -> base_tune (when has stoich/VE tables, not DynoAI-generated)
    PVV (DynoAI patch)   -> patches   (generated by us, marked accordingly)
    PTI (engine spec)    -> pulls    (rare; we keep it bound to the iteration)
    Generic CSV          -> pulls    (falls back to the csv_parser)
    Unknown              -> rejected

The return shape is intentionally small and JSON-friendly so the UI can
display a "we think this is X" badge per file and let the user override.
"""

from __future__ import annotations

import logging
from dataclasses import asdict, dataclass
from enum import Enum
from typing import Any, Optional

from api.services.parsers.dynojet_txt_parser import looks_like_dynojet_txt
from api.services.parsers.pvv_signature import compute_pvv_signature

logger = logging.getLogger(__name__)

__all__ = ["FileType", "Classification", "classify_upload"]

WP8_MAGIC = b"\xfe\xce\xfa\xce"
HEAD_BYTES = 64 * 1024


class FileType(str, Enum):
    WP8 = "wp8"
    PVV = "pvv"
    DYNOJET_TXT = "dynojet_txt"
    POWERVISION_CSV = "powervision_csv"
    GENERIC_CSV = "generic_csv"
    PTI = "pti"
    UNKNOWN = "unknown"


@dataclass
class Classification:
    """Result of a sniffer call. `routed_to` is the workspace slot."""

    file_type: str
    confidence: float
    routed_to: str
    detail: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def classify_upload(
    data: bytes,
    filename: str,
    override: Optional[str] = None,
) -> dict[str, Any]:
    """Sniff `data` and return routing info.

    `override` (optional) is a slot hint from the user: "base_tune" |
    "patches" | "pulls". When set, we still sniff to get the file_type,
    but we keep the user's slot choice.
    """
    if not data:
        return Classification(
            file_type=FileType.UNKNOWN.value,
            confidence=0.0,
            routed_to="rejected",
            detail={"reason": "empty file"},
        ).to_dict()

    head = data[:HEAD_BYTES]

    if head.startswith(WP8_MAGIC):
        out = _classify_wp8(data, filename)
    elif _looks_like_xml(head):
        out = _classify_xml(data, filename)
    else:
        try:
            text = head.decode("utf-8", errors="replace")
        except Exception:
            text = ""

        if text.lstrip().startswith("Dynojet Power Vision Log File"):
            out = _classify_pv_csv(data, filename, text)
        elif looks_like_dynojet_txt(text):
            out = _classify_dynojet_txt(data, filename, text)
        elif _looks_like_csv(text):
            out = _classify_generic_csv(data, filename, text)
        elif _looks_like_pti(text):
            out = _classify_pti(data, filename, text)
        else:
            out = Classification(
                file_type=FileType.UNKNOWN.value,
                confidence=0.1,
                routed_to="rejected",
                detail={"reason": "unrecognized content"},
            )

    if override in {"base_tune", "patches", "pulls"}:
        out = Classification(
            file_type=out.file_type,
            confidence=out.confidence,
            routed_to=override,
            detail={**out.detail, "override": override},
        )

    return out.to_dict()


# -----------------------------------------------------------------------------
# WP8
# -----------------------------------------------------------------------------


def _classify_wp8(data: bytes, filename: str) -> Classification:
    return Classification(
        file_type=FileType.WP8.value,
        confidence=0.99,
        routed_to="pulls",
        detail={"size": len(data), "filename": filename},
    )


# -----------------------------------------------------------------------------
# XML / PVV
# -----------------------------------------------------------------------------


def _looks_like_xml(head: bytes) -> bool:
    stripped = head.lstrip()
    return stripped.startswith(b"<?xml") or stripped.startswith(b"<")


def _classify_xml(data: bytes, filename: str) -> Classification:
    try:
        text = data.decode("utf-8", errors="replace")
    except Exception:
        return Classification(
            file_type=FileType.UNKNOWN.value,
            confidence=0.1,
            routed_to="rejected",
            detail={"reason": "cannot decode xml"},
        )

    lower = text.lower()
    if "<pvv" not in lower:
        return Classification(
            file_type=FileType.UNKNOWN.value,
            confidence=0.1,
            routed_to="rejected",
            detail={"reason": "xml but not a PVV"},
        )

    signature = compute_pvv_signature(text)
    is_dynoai_patch = _is_dynoai_generated(text) or _mentions_dynoai_correction(text)

    is_patch = is_dynoai_patch or "correction" in (filename or "").lower()

    slot = "patches" if is_patch else "base_tune"
    return Classification(
        file_type=FileType.PVV.value,
        confidence=0.95 if signature else 0.6,
        routed_to=slot,
        detail={
            "signature": signature,
            "is_dynoai_patch": bool(is_dynoai_patch),
            "filename": filename,
        },
    )


def _is_dynoai_generated(text: str) -> bool:
    return "dynoai" in text.lower() or "<!-- generated by dynoai" in text.lower()


def _mentions_dynoai_correction(text: str) -> bool:
    return 'name="VE Correction"' in text or 'name="Dynoai' in text


# -----------------------------------------------------------------------------
# Dynojet TXT
# -----------------------------------------------------------------------------


def _classify_dynojet_txt(data: bytes, filename: str, text: str) -> Classification:
    return Classification(
        file_type=FileType.DYNOJET_TXT.value,
        confidence=0.9,
        routed_to="pulls",
        detail={"size": len(data), "filename": filename},
    )


# -----------------------------------------------------------------------------
# Power Vision CSV
# -----------------------------------------------------------------------------


def _classify_pv_csv(data: bytes, filename: str, text: str) -> Classification:
    return Classification(
        file_type=FileType.POWERVISION_CSV.value,
        confidence=0.95,
        routed_to="pulls",
        detail={"size": len(data), "filename": filename},
    )


# -----------------------------------------------------------------------------
# Generic CSV
# -----------------------------------------------------------------------------


def _looks_like_csv(text: str) -> bool:
    head = text[:4000]
    lines = [line for line in head.splitlines() if line.strip()]
    if len(lines) < 2:
        return False
    comma_lines = sum(1 for line in lines if line.count(",") >= 2)
    return comma_lines >= max(2, len(lines) // 2)


def _classify_generic_csv(data: bytes, filename: str, text: str) -> Classification:
    first_line = text.splitlines()[0] if text else ""
    return Classification(
        file_type=FileType.GENERIC_CSV.value,
        confidence=0.6,
        routed_to="pulls",
        detail={
            "size": len(data),
            "filename": filename,
            "header": first_line[:200],
        },
    )


# -----------------------------------------------------------------------------
# PTI (engine spec)
# -----------------------------------------------------------------------------


def _looks_like_pti(text: str) -> bool:
    head = text[:2000].lower()
    return "performance trends" in head or "engine analyzer" in head


def _classify_pti(data: bytes, filename: str, text: str) -> Classification:
    return Classification(
        file_type=FileType.PTI.value,
        confidence=0.8,
        routed_to="pulls",
        detail={"size": len(data), "filename": filename},
    )
