"""End-to-end slice test for the InjectorScalarRebase tool.

This is the first lifted tool that mutates *scalars* in addition to VE
tables, so the test asserts on a richer integrity check: four item ids
may change (2 scalars + 2 VE tables), nothing else.

Reference output generated by running
`tools/seanbike/patch_stock_injectors_110_preserve_wot.py` on
`v_pc_advanced_translation.pvv` (the seanbike PVV that uses TPS-based VE
table names and has the matching injector + displacement scalars).

Asserts:

  1. Byte-identical SHA against the seanbike reference.
  2. Idempotency.
  3. plan().predicted_cells_changed == actual cells_changed.
  4. Exactly four item ids change: 2 VE tables + 2 scalars.
  5. Max_ve_block hard-fails when set tight enough to trip.
  6. Manifest captures scalars + preserve_factor + blend zones + warnings.
  7. Aggressive injector_gps trips the sanity-range ValueError in plan.
  8. Profile override changes the preserve_factor and thus the SHA.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from dynoai.diagnostics.detector import DetectionContext
from dynoai.diagnostics.finding import Finding
from dynoai.tools.injector_scalar_rebase import (
    DEFAULT_DISPLACEMENT_ID,
    DEFAULT_INJECTOR_ID,
    DEFAULT_VE_FRONT_ID,
    DEFAULT_VE_REAR_ID,
    InjectorScalarRebaseTool,
    TOOL_NAME,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
INPUT_PVV = (
    REPO_ROOT
    / "vehicles"
    / "seanbike"
    / "sessions"
    / "dai_2026_0518_pcv_bake_verify"
    / "iterations"
    / "iter_0"
    / "patches"
    / "v_pc_advanced_translation.pvv"
)
REFERENCE_INPUT_SHA = (
    "bbeec7f4d22aa49aa1daed0a193d2c12e2c020f0088fff85c393a41153362fae"
)
REFERENCE_OUTPUT_SHA = (
    "fdb47e9093da1be9f3ce19a1b5c85af1b18763d2fd876f66d26ae2dd9a2e62a3"
)
REFERENCE_TOTAL_CELLS_CHANGED = 868

# preserve_factor = (old_disp / old_inj) * (new_inj / new_disp)
#                 = (103.0 / 31.07) * (3.91 * 3600/453.59237 / 110.0)
# The injector ALSO shifts slightly: 31.07 -> 31.0322 lb/hr after the g/s
# conversion, so the factor is not exactly 103/110.
REFERENCE_PRESERVE_FACTOR = 0.9352264992801496


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.fixture(scope="module")
def fixture_input_sha() -> str:
    assert INPUT_PVV.exists(), f"missing fixture: {INPUT_PVV}"
    sha = _sha256(INPUT_PVV)
    assert sha == REFERENCE_INPUT_SHA, (
        f"input drifted: got {sha}, expected {REFERENCE_INPUT_SHA}"
    )
    return sha


def _make_ctx(iter_dir: Path, *, profile: dict | None = None) -> DetectionContext:
    iter_dir.mkdir(parents=True, exist_ok=True)
    return DetectionContext(
        base_pvv_path=INPUT_PVV,
        vehicle_profile=profile or {"id": "seanbike", "tool_overrides": {}},
        iteration_dir=iter_dir,
    )


def _make_finding(**overrides) -> Finding:
    params = {
        "kind": "injector_calibration",
        "severity": 0.75,
        "confidence": 0.9,
        "evidence": {
            "old_injector_lb_hr": 31.07,
            "old_displacement_cid": 103.0,
            "new_displacement_cid": 110.0,
        },
        "suggested_tool": TOOL_NAME,
        "tool_params": {},
        "source": "injector_mismatch_detector",
    }
    params.update(overrides)
    return Finding(**params)


def test_lifted_tool_matches_seanbike_reference_sha(tmp_path, fixture_input_sha):
    """Lifted tool must produce byte-identical output to the seanbike script."""
    tool = InjectorScalarRebaseTool()
    ctx = _make_ctx(tmp_path / "iter_ref")
    finding = _make_finding()

    plan = tool.plan(finding, ctx)
    result = tool.apply(plan, ctx)

    assert result.success, f"apply failed: {result.gates_failed}"
    assert result.sha256 == REFERENCE_OUTPUT_SHA, (
        f"byte drift from seanbike injector reference: got {result.sha256}, "
        f"expected {REFERENCE_OUTPUT_SHA}"
    )
    assert result.cells_changed == REFERENCE_TOTAL_CELLS_CHANGED


def test_idempotent_apply_produces_same_sha(tmp_path, fixture_input_sha):
    """Same plan twice -> identical bytes."""
    tool = InjectorScalarRebaseTool()
    ctx_a = _make_ctx(tmp_path / "iter_a")
    ctx_b = _make_ctx(tmp_path / "iter_b")
    finding = _make_finding()

    result_a = tool.apply(tool.plan(finding, ctx_a), ctx_a)
    result_b = tool.apply(tool.plan(finding, ctx_b), ctx_b)

    assert result_a.success and result_b.success
    assert result_a.sha256 == result_b.sha256


def test_plan_apply_parity(tmp_path, fixture_input_sha):
    tool = InjectorScalarRebaseTool()
    ctx = _make_ctx(tmp_path / "iter_parity")
    finding = _make_finding()

    plan = tool.plan(finding, ctx)
    result = tool.apply(plan, ctx)

    assert result.success
    assert plan.predicted_cells_changed == result.cells_changed
    assert plan.predicted_max_delta["preserve_factor"] == pytest.approx(
        REFERENCE_PRESERVE_FACTOR, abs=1e-6
    )


def test_four_item_ids_change(tmp_path, fixture_input_sha):
    """Exactly 2 scalars + 2 VE tables change; nothing else."""
    tool = InjectorScalarRebaseTool()
    ctx = _make_ctx(tmp_path / "iter_integrity")
    finding = _make_finding()

    result = tool.apply(tool.plan(finding, ctx), ctx)

    assert result.success
    assert set(result.extra["changed_ids"]) == {
        DEFAULT_VE_FRONT_ID,
        DEFAULT_VE_REAR_ID,
        DEFAULT_INJECTOR_ID,
        DEFAULT_DISPLACEMENT_ID,
    }


def test_max_ve_block_fires_on_aggressive_displacement(tmp_path, fixture_input_sha):
    """A very small displacement target inflates preserve_factor and trips the block.

    preserve_factor = (old_disp/old_inj) * (new_inj/new_disp). With seanbike's
    base scalars (~31.07 lb/hr, 103 CID), a target displacement of 96 CID
    pushes preserve_factor to ~1.073, scaling already-high VE cells past
    the 170 hard block. The tool must fail closed.
    """
    tool = InjectorScalarRebaseTool()
    ctx = _make_ctx(tmp_path / "iter_block")
    finding = _make_finding(
        tool_params={
            "displacement_cid": 96.0,
            "max_ve_block": 130.0,  # tighter than the seanbike default; trip it
        }
    )

    plan = tool.plan(finding, ctx)
    result = tool.apply(plan, ctx)

    assert result.success is False
    assert any(gf.gate == "max_ve_block" for gf in result.gates_failed)
    assert plan.output_pvv_path.exists() is False
    assert result.sha256 is None


def test_sanity_range_rejects_unrealistic_injector(tmp_path, fixture_input_sha):
    """Out-of-range injector_gps must raise during plan()."""
    tool = InjectorScalarRebaseTool()
    ctx = _make_ctx(tmp_path / "iter_sanity")
    finding = _make_finding(tool_params={"injector_gps": 0.5})  # ~4 lb/hr, way too small

    with pytest.raises(ValueError, match="injector"):
        tool.plan(finding, ctx)


def test_manifest_captures_scalars_and_preserve_factor(tmp_path, fixture_input_sha):
    tool = InjectorScalarRebaseTool()
    ctx = _make_ctx(tmp_path / "iter_manifest")
    finding = _make_finding()

    result = tool.apply(tool.plan(finding, ctx), ctx)

    assert result.success
    manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
    assert manifest["kind"] == "injector_scalar_rebase_patch"
    assert manifest["output"]["sha256"] == REFERENCE_OUTPUT_SHA
    assert manifest["scalars"]["old_displacement_cid"] == pytest.approx(103.0)
    assert manifest["scalars"]["new_displacement_cid"] == pytest.approx(110.0)
    assert manifest["scalars"]["preserve_factor"] == pytest.approx(
        REFERENCE_PRESERVE_FACTOR, abs=1e-6
    )
    # Manifest also records the actual scalar shifts
    assert manifest["scalars"]["old_injector_lb_hr"] == pytest.approx(31.07)
    assert manifest["scalars"]["new_injector_lb_hr"] == pytest.approx(31.0322, abs=1e-3)
    assert manifest["blend_zones"]["idle_rpm_krpm"] == 1.5
    assert manifest["safety_thresholds"]["max_ve_block"] == 170.0
    assert manifest["summary"]["total_cells_changed"] == REFERENCE_TOTAL_CELLS_CHANGED
    assert "table_stats" in manifest["summary"]
    assert len(manifest["summary"]["table_stats"]) == 2
    assert manifest["finding"]["kind"] == "injector_calibration"


def test_profile_override_changes_blend_zone(tmp_path, fixture_input_sha):
    """A profile override on idle_rpm_krpm changes the patch bytes."""
    tool = InjectorScalarRebaseTool()
    ctx_default = _make_ctx(tmp_path / "iter_default")
    ctx_override = _make_ctx(
        tmp_path / "iter_override",
        profile={
            "id": "seanbike",
            "tool_overrides": {TOOL_NAME: {"idle_rpm_krpm": 2.5}},
        },
    )
    finding = _make_finding()

    result_default = tool.apply(tool.plan(finding, ctx_default), ctx_default)
    result_override = tool.apply(tool.plan(finding, ctx_override), ctx_override)

    assert result_default.success and result_override.success
    assert result_default.sha256 == REFERENCE_OUTPUT_SHA
    assert result_override.sha256 != REFERENCE_OUTPUT_SHA
