"""Tests for api.services.ingest.sniffer."""

from __future__ import annotations

import pytest

from api.services.ingest.sniffer import FileType, classify_upload


def test_wp8_magic_classified_as_wp8():
    data = b"\xfe\xce\xfa\xce" + b"\x00" * 100
    out = classify_upload(data, "run.wp8")
    assert out["file_type"] == FileType.WP8.value
    assert out["routed_to"] == "pulls"


def test_pvv_without_dynoai_marker_is_base_tune():
    data = (
        b'<?xml version="1.0"?><PVV>'
        b'<Item name="tbl_ve_tps_based_front_cyl">'
        b'<Cell value="1.0"/></Item></PVV>'
    )
    out = classify_upload(data, "tune.pvv")
    assert out["file_type"] == FileType.PVV.value
    assert out["routed_to"] == "base_tune"
    assert out["detail"]["is_dynoai_patch"] is False
    assert out["detail"]["signature"]


def test_dynoai_patch_routes_to_patches():
    data = (
        b'<?xml version="1.0"?>'
        b"<!-- generated by dynoai v1.0 -->"
        b'<PVV><Item name="VE Correction"><Cell value="1.02"/></Item></PVV>'
    )
    out = classify_upload(data, "ve_patch.pvv")
    assert out["file_type"] == FileType.PVV.value
    assert out["routed_to"] == "patches"


def test_dynojet_txt_classification():
    data = (
        b"Time (s)\tSpeed (mph)\tPower (hp)\tLC1 AFR\tLC2 AFR\n"
        b"0.5\t30.2\t10.3\t13.5\t13.3\n"
        b"1.0\t41.5\t22.1\t13.1\t13.0\n"
        b"1.5\t55.4\t35.9\t12.8\t12.6\n"
    )
    out = classify_upload(data, "pull.txt")
    assert out["file_type"] == FileType.DYNOJET_TXT.value
    assert out["routed_to"] == "pulls"


def test_power_vision_csv_classification():
    data = b'Dynojet Power Vision Log File\n"Format:","Pro-XY CSV 1.0.0"\n'
    out = classify_upload(data, "log.csv")
    assert out["file_type"] == FileType.POWERVISION_CSV.value
    assert out["routed_to"] == "pulls"


def test_empty_upload_rejected():
    out = classify_upload(b"", "anything.bin")
    assert out["routed_to"] == "rejected"


def test_unknown_bytes_rejected():
    out = classify_upload(b"\x01\x02\x03binary garbage", "weird.bin")
    assert out["routed_to"] == "rejected"


def test_override_honored_even_when_type_differs():
    data = b"\xfe\xce\xfa\xce" + b"\x00" * 20
    out = classify_upload(data, "run.wp8", override="base_tune")
    assert out["file_type"] == FileType.WP8.value
    assert out["routed_to"] == "base_tune"
    assert out["detail"]["override"] == "base_tune"


def test_generic_csv_falls_back_to_pulls():
    data = b"rpm,map,afr\n2000,50,13.2\n3000,60,12.9\n4000,70,12.7\n"
    out = classify_upload(data, "generic.csv")
    assert out["file_type"] == FileType.GENERIC_CSV.value
    assert out["routed_to"] == "pulls"
