"""Tests for api.services.ingest.sniffer."""

from __future__ import annotations

import pytest

from api.services.ingest.sniffer import FileType, classify_upload


def test_wp8_magic_classified_as_wp8():
    data = b"\xfe\xce\xfa\xce" + b"\x00" * 100
    out = classify_upload(data, "run.wp8")
    assert out["file_type"] == FileType.WP8.value
    assert out["routed_to"] == "pulls"


def test_pvv_without_dynoai_marker_is_base_tune():
    data = (
        b'<?xml version="1.0"?><PVV>'
        b'<Item name="tbl_ve_tps_based_front_cyl">'
        b'<Cell value="1.0"/></Item></PVV>'
    )
    out = classify_upload(data, "tune.pvv")
    assert out["file_type"] == FileType.PVV.value
    assert out["routed_to"] == "base_tune"
    assert out["detail"]["is_dynoai_patch"] is False
    assert out["detail"]["signature"]


def test_dynoai_patch_routes_to_patches():
    data = (
        b'<?xml version="1.0"?>'
        b"<!-- generated by dynoai v1.0 -->"
        b'<PVV><Item name="VE Correction"><Cell value="1.02"/></Item></PVV>'
    )
    out = classify_upload(data, "ve_patch.pvv")
    assert out["file_type"] == FileType.PVV.value
    assert out["routed_to"] == "patches"


def test_dynojet_txt_classification():
    data = (
        b"Time (s)\tSpeed (mph)\tPower (hp)\tLC1 AFR\tLC2 AFR\n"
        b"0.5\t30.2\t10.3\t13.5\t13.3\n"
        b"1.0\t41.5\t22.1\t13.1\t13.0\n"
        b"1.5\t55.4\t35.9\t12.8\t12.6\n"
    )
    out = classify_upload(data, "pull.txt")
    assert out["file_type"] == FileType.DYNOJET_TXT.value
    assert out["routed_to"] == "pulls"


def test_power_vision_csv_classification():
    data = b'Dynojet Power Vision Log File\n"Format:","Pro-XY CSV 1.0.0"\n'
    out = classify_upload(data, "log.csv")
    assert out["file_type"] == FileType.POWERVISION_CSV.value
    assert out["routed_to"] == "pulls"


def test_empty_upload_rejected():
    out = classify_upload(b"", "anything.bin")
    assert out["routed_to"] == "rejected"


def test_unknown_bytes_rejected():
    out = classify_upload(b"\x01\x02\x03binary garbage", "weird.bin")
    assert out["routed_to"] == "rejected"


def test_override_honored_even_when_type_differs():
    data = b"\xfe\xce\xfa\xce" + b"\x00" * 20
    out = classify_upload(data, "run.wp8", override="base_tune")
    assert out["file_type"] == FileType.WP8.value
    assert out["routed_to"] == "base_tune"
    assert out["detail"]["override"] == "base_tune"


def test_generic_csv_falls_back_to_pulls():
    data = b"rpm,map,afr\n2000,50,13.2\n3000,60,12.9\n4000,70,12.7\n"
    out = classify_upload(data, "generic.csv")
    assert out["file_type"] == FileType.GENERIC_CSV.value
    assert out["routed_to"] == "pulls"


# -----------------------------------------------------------------------------
# BOM tolerance: some Windows tools (PowerShell Set-Content -Encoding UTF8,
# certain editors) prepend a BOM to text files. The classifier must still
# recognise these as PVV/XML rather than rejecting them as binary garbage.
# -----------------------------------------------------------------------------


def test_pvv_with_utf8_bom_classified_as_pvv():
    data = (
        b"\xef\xbb\xbf"  # UTF-8 BOM
        b'<?xml version="1.0"?><PVV>'
        b'<Item name="tbl_ve"><Cell value="1.0"/></Item></PVV>'
    )
    out = classify_upload(data, "tune.pvv")
    assert out["file_type"] == FileType.PVV.value
    assert out["routed_to"] == "base_tune"


def test_pvv_with_utf16_le_bom_classified_as_pvv():
    # UTF-16 LE BOM (FF FE) followed by null-padded ASCII via Python's
    # built-in encode (yields the same bytes as PowerShell's UTF-16 output).
    text = '<PVV><Item name="VE Correction"><Cell value="1.02"/></Item></PVV>'
    data = b"\xff\xfe" + text.encode("utf-16-le")
    out = classify_upload(data, "patch.pvv")
    assert out["file_type"] == FileType.PVV.value
    # `VE Correction` content marks it as a DynoAI-style patch.
    assert out["routed_to"] == "patches"


def test_pvv_with_utf16_be_bom_classified_as_pvv():
    text = "<PVV><Item><Cell/></Item></PVV>"
    data = b"\xfe\xff" + text.encode("utf-16-be")
    out = classify_upload(data, "tune.pvv")
    assert out["file_type"] == FileType.PVV.value


def test_non_pvv_xml_with_bom_still_rejected():
    data = b"\xef\xbb\xbf<?xml version='1.0'?><html>not a pvv</html>"
    out = classify_upload(data, "wrong.xml")
    assert out["file_type"] == FileType.UNKNOWN.value
    assert out["routed_to"] == "rejected"
