"""End-to-end slice test for the AccelEnrich tool.

Reference output generated by running tools/seanbike/patch_accel_enrich.py
on the seanbike base.pvv with default args.

Asserts:

  1. Byte-identical SHA against the seanbike reference (lower direction).
  2. Idempotency.
  3. plan().predicted_cells_changed == actual.
  4. Only the target table id changes.
  5. Tight max_delta_gate aborts without writing on overcommit.
  6. Manifest captures policy + cell records + direction tag.
  7. Bidirectional: raising hot cells via a higher target_hot produces a
     different (also byte-stable) patch with direction="raise".
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from dynoai.diagnostics.detector import DetectionContext
from dynoai.diagnostics.detectors.accel_transient import AccelTransientDetector
from dynoai.diagnostics.dispatcher import TuningDispatcher
from dynoai.diagnostics.finding import Finding
from dynoai.tools.accel_enrich import (
    DEFAULT_TARGET_ITEM_ID,
    AccelEnrichTool,
    TOOL_NAME,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
SEANBIKE_BASE_PVV = (
    REPO_ROOT
    / "vehicles"
    / "seanbike"
    / "sessions"
    / "dai_2026_0518_pcv_bake_verify"
    / "base_tune"
    / "base.pvv"
)
REFERENCE_INPUT_SHA = (
    "79766f19fb4db3cff0b64f3952ad9d67f991515b5544c381177f770de110a612"
)
# Captured from tools/seanbike/patch_accel_enrich.py with defaults
# (--hot-threshold=140, --target-hot=0.3) on the seanbike base.pvv.
REFERENCE_OUTPUT_SHA = (
    "68f44cfc9a1be554ccbefa39ccd6c178b67252122db0ff8b2b78308cf6108891"
)
REFERENCE_CELLS_CHANGED = 7  # cells at T >= 147 in the seanbike base table


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.fixture(scope="module")
def fixture_input_sha() -> str:
    assert SEANBIKE_BASE_PVV.exists(), f"missing fixture: {SEANBIKE_BASE_PVV}"
    sha = _sha256(SEANBIKE_BASE_PVV)
    assert sha == REFERENCE_INPUT_SHA, (
        f"base.pvv drifted: got {sha}, expected {REFERENCE_INPUT_SHA}"
    )
    return sha


def _make_ctx(iter_dir: Path, *, profile: dict | None = None) -> DetectionContext:
    iter_dir.mkdir(parents=True, exist_ok=True)
    return DetectionContext(
        base_pvv_path=SEANBIKE_BASE_PVV,
        vehicle_profile=profile or {"id": "seanbike", "tool_overrides": {}},
        iteration_dir=iter_dir,
    )


def _make_finding(**overrides) -> Finding:
    params = {
        "kind": "accel_rich_spike",
        "severity": 0.65,
        "confidence": 0.85,
        "evidence": {"hot_threshold": 140.0, "target_hot": 0.30},
        "suggested_tool": TOOL_NAME,
        "tool_params": {},
        "source": "accel_rich_detector",
    }
    params.update(overrides)
    return Finding(**params)


def test_lifted_tool_matches_seanbike_reference_sha(tmp_path, fixture_input_sha):
    """Lifted tool must produce byte-identical output to patch_accel_enrich.py."""
    tool = AccelEnrichTool()
    ctx = _make_ctx(tmp_path / "iter_ref")
    finding = _make_finding()

    plan = tool.plan(finding, ctx)
    result = tool.apply(plan, ctx)

    assert result.success, f"apply failed: {result.gates_failed}"
    assert result.sha256 == REFERENCE_OUTPUT_SHA, (
        f"byte drift from seanbike accel reference: got {result.sha256}, "
        f"expected {REFERENCE_OUTPUT_SHA}"
    )
    assert result.cells_changed == REFERENCE_CELLS_CHANGED
    assert result.extra["direction"] == "lower"


def test_idempotent_apply_produces_same_sha(tmp_path, fixture_input_sha):
    """Same plan twice -> identical bytes."""
    tool = AccelEnrichTool()
    ctx_a = _make_ctx(tmp_path / "iter_a")
    ctx_b = _make_ctx(tmp_path / "iter_b")
    finding = _make_finding()

    result_a = tool.apply(tool.plan(finding, ctx_a), ctx_a)
    result_b = tool.apply(tool.plan(finding, ctx_b), ctx_b)

    assert result_a.success and result_b.success
    assert result_a.sha256 == result_b.sha256


def test_plan_apply_parity(tmp_path, fixture_input_sha):
    tool = AccelEnrichTool()
    ctx = _make_ctx(tmp_path / "iter_parity")
    finding = _make_finding()

    plan = tool.plan(finding, ctx)
    result = tool.apply(plan, ctx)

    assert result.success
    assert plan.predicted_cells_changed == result.cells_changed
    assert plan.predicted_max_delta["enrich_mult"] > 0.0


def test_only_target_table_changes(tmp_path, fixture_input_sha):
    tool = AccelEnrichTool()
    ctx = _make_ctx(tmp_path / "iter_integrity")
    finding = _make_finding()

    result = tool.apply(tool.plan(finding, ctx), ctx)

    assert result.success
    assert result.extra["changed_ids"] == [DEFAULT_TARGET_ITEM_ID]


def test_tight_max_delta_gate_aborts_without_writing(tmp_path, fixture_input_sha):
    """Natural deltas reach 0.25; a gate at 0.10 must trip."""
    tool = AccelEnrichTool()
    ctx = _make_ctx(tmp_path / "iter_abort")
    finding = _make_finding(tool_params={"gate_max_delta": 0.10})

    plan = tool.plan(finding, ctx)
    result = tool.apply(plan, ctx)

    assert result.success is False
    assert any(gf.gate == "max_delta" for gf in result.gates_failed)
    assert plan.output_pvv_path.exists() is False
    assert result.sha256 is None


def test_manifest_records_policy_and_cells_and_direction(tmp_path, fixture_input_sha):
    tool = AccelEnrichTool()
    ctx = _make_ctx(tmp_path / "iter_manifest")
    finding = _make_finding()

    result = tool.apply(tool.plan(finding, ctx), ctx)

    assert result.success
    manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
    assert manifest["kind"] == "accel_enrich_patch"
    assert manifest["target_item_id"] == DEFAULT_TARGET_ITEM_ID
    assert manifest["direction"] == "lower"
    assert manifest["output"]["sha256"] == REFERENCE_OUTPUT_SHA
    assert manifest["patch_policy"]["target_hot"] == 0.30
    assert manifest["summary"]["cells_changed"] == REFERENCE_CELLS_CHANGED
    assert manifest["summary"]["mean_signed_delta"] < 0  # net lower
    assert len(manifest["cells"]) == REFERENCE_CELLS_CHANGED
    for cell in manifest["cells"]:
        assert cell["temp_axis"] >= 140.0
    assert manifest["finding"]["kind"] == "accel_rich_spike"


def test_bidirectional_raising_with_higher_target_hot(tmp_path, fixture_input_sha):
    """Setting target_hot above the current cell values raises instead of lowering.

    The seanbike `raise_accel_enrich.py` script is exactly this — same algorithm,
    different default direction. One tool serves both seanbike scripts.
    """
    tool = AccelEnrichTool()
    ctx = _make_ctx(tmp_path / "iter_raise")
    # Hot cells in seanbike base are around 0.36-0.92; target 1.5 raises them.
    finding = _make_finding(
        kind="accel_lean_lag",
        tool_params={"target_hot": 1.50},
    )

    plan = tool.plan(finding, ctx)
    result = tool.apply(plan, ctx)

    assert result.success, f"apply failed: {result.gates_failed}"
    assert result.extra["direction"] == "raise"
    assert result.sha256 != REFERENCE_OUTPUT_SHA  # different from "lower" default
    assert result.cells_changed > 0
    manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
    assert manifest["direction"] == "raise"
    assert manifest["summary"]["mean_signed_delta"] > 0  # net raise
    assert manifest["finding"]["kind"] == "accel_lean_lag"


def test_profile_override_changes_target_hot(tmp_path, fixture_input_sha):
    """A profile override on target_hot changes the patch bytes."""
    tool = AccelEnrichTool()
    ctx_default = _make_ctx(tmp_path / "iter_default")
    ctx_override = _make_ctx(
        tmp_path / "iter_override",
        profile={
            "id": "seanbike",
            "tool_overrides": {TOOL_NAME: {"target_hot": 0.50}},
        },
    )
    finding = _make_finding()

    result_default = tool.apply(tool.plan(finding, ctx_default), ctx_default)
    result_override = tool.apply(tool.plan(finding, ctx_override), ctx_override)

    assert result_default.success and result_override.success
    assert result_default.sha256 == REFERENCE_OUTPUT_SHA
    assert result_override.sha256 != REFERENCE_OUTPUT_SHA


# ---------------------------------------------------------------------------
# End-to-end via AccelTransientDetector (bidirectional rich/lean).
# ---------------------------------------------------------------------------


def test_accel_transient_detector_fires_lean_lag_on_seanbike(tmp_path, fixture_input_sha):
    """seanbike base.pvv accel enrichment hot cells go down to 0.36 - below
    the 0.50 lean threshold. Detector must emit accel_lean_lag."""
    detector = AccelTransientDetector(
        lean_min_mult=0.50,
        rich_max_mult=1.20,
    )
    ctx = _make_ctx(tmp_path / "iter_detect")

    findings = detector.detect(ctx)

    # seanbike hot cells: 0.92, 0.77, 0.62, 0.53, 0.44, 0.38, 0.36 ->
    # min=0.36 (triggers lean), max=0.92 (does NOT trigger rich at 1.20).
    assert len(findings) == 1
    finding = findings[0]
    assert finding.kind == "accel_lean_lag"
    assert finding.source == "accel_transient_detector"
    assert finding.suggested_tool == TOOL_NAME
    assert finding.evidence["hot_min"] == pytest.approx(0.36, abs=0.01)
    # target_hot bound to the detector's lean_target_mult so the tool
    # raises hot cells toward it.
    assert finding.tool_params["target_hot"] > finding.evidence["hot_min"]


def test_accel_transient_detector_quiet_when_in_range(tmp_path, fixture_input_sha):
    """Loosen both thresholds past the seanbike data range - nothing fires."""
    detector = AccelTransientDetector(
        lean_min_mult=0.20,
        rich_max_mult=3.00,
    )
    ctx = _make_ctx(tmp_path / "iter_quiet")

    findings = detector.detect(ctx)

    assert findings == []


def test_dispatcher_routes_accel_lean_to_plan(tmp_path, fixture_input_sha):
    """Full pipeline: seanbike base.pvv -> AccelTransientDetector ->
    dispatcher -> accel_enrich. Detector binds target_hot=lean_target_mult
    in tool_params, so the patch raises hot cells (direction=raise)."""
    tool = AccelEnrichTool()
    dispatcher = TuningDispatcher(
        detectors=[AccelTransientDetector()],
        tools={tool.name: tool},
    )
    iter_dir = tmp_path / "iter_e2e"
    iter_dir.mkdir(parents=True, exist_ok=True)
    ctx = DetectionContext(
        base_pvv_path=SEANBIKE_BASE_PVV,
        vehicle_profile={"id": "seanbike", "tool_overrides": {}},
        iteration_dir=iter_dir,
    )

    decision = dispatcher.step(ctx)

    assert decision.plan is not None
    assert decision.plan.tool == TOOL_NAME
    assert decision.plan.finding.kind == "accel_lean_lag"
    result = dispatcher.apply(decision.plan, ctx)
    assert result.success
    # Detector raised cells toward lean_target_mult (0.90 default).
    assert result.extra["direction"] == "raise"
    # Different from the lower-direction reference SHA the tool's defaults
    # produce, because the detector overrides target_hot.
    assert result.sha256 != REFERENCE_OUTPUT_SHA
